version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: voting

  frontend:
    build:
      context: .
      dockerfile: node-frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./node-frontend:/app
      - /app/node_modules
      - ./_opentelemetry-js:/app/_opentelemetry-js
      - /app/_opentelemetry-js/node_modules

  service-gateway:
    build:
      context: .
      dockerfile: python-service-gateway/Dockerfile
    container_name: service-gateway
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
    volumes:
      - ./python-service-gateway:/app
      - ./_opentelemetry-py:/app/_opentelemetry-py
    depends_on:
      - service-blue
      - service-green

  service-blue:
    build:
      context: .
      dockerfile: node-service-blue/Dockerfile
    container_name: service-blue
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
    volumes:
      - ./node-service-blue:/app
      - /app/node_modules
      - ./_opentelemetry-js:/app/_opentelemetry-js
      - /app/_opentelemetry-js/node_modules
    depends_on:
      - mongodb

  service-green:
    build:
      context: .
      dockerfile: python-service-green/Dockerfile
    container_name: service-green
    ports:
      - "3020:3020"
    environment:
      - FLASK_ENV=development
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
    volumes:
      - ./python-service-green:/app
      - ./_opentelemetry-py:/app/_opentelemetry-py
    depends_on:
      - mongodb
