version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: voting

  frontend:
    build:
      context: .
      dockerfile: node-frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318/v1/traces
      - GATEWAY_URL=http://service-gateway:5000
    volumes:
      - ./node-frontend:/app
      - /app/node_modules
      - ./_opentelemetry-js:/app/_opentelemetry-js
      - /app/_opentelemetry-js/node_modules
    depends_on:
      - service-gateway

  service-gateway:
    build:
      context: .
      dockerfile: python-service-gateway/Dockerfile
    container_name: service-gateway
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SERVICE_BLUE_URL=http://service-blue:3010
      - SERVICE_GREEN_URL=http://service-green:3020
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318/v1/traces
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
    volumes:
      - ./python-service-gateway:/app
      - ./_opentelemetry-py:/app/_opentelemetry-py
    depends_on:
      - service-blue
      - service-green

  service-blue:
    build:
      context: .
      dockerfile: node-service-blue/Dockerfile
    container_name: service-blue
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://database:27017/voting
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318/v1/traces
    volumes:
      - ./node-service-blue:/app
      - /app/node_modules
      - ./_opentelemetry-js:/app/_opentelemetry-js
      - /app/_opentelemetry-js/node_modules
    depends_on:
      - mongodb

  service-green:
    build:
      context: .
      dockerfile: python-service-green/Dockerfile
    container_name: service-green
    ports:
      - "3020:3020"
    environment:
      - FLASK_ENV=development
      - MONGODB_URL=mongodb://database:27017/voting
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://opentelemetry-collector:4318/v1/traces
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
    volumes:
      - ./python-service-green:/app
      - ./_opentelemetry-py:/app/_opentelemetry-py
    depends_on:
      - mongodb
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # UI
      - "5317:4317"    # OTLP gRPC
      - "5318:4318"    # OTLP HTTP
      - "5778:5778"    # Configs (sampling, etc.)
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    depends_on:
      - opentelemetry-collector
  
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    container_name: opentelemetry-collector
    ports:
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
      - "13133:13133"  # health_check extension
      - "1777:1777"    # pprof extension
      - "55679:55679"  # zpages extension
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./_opentelemetry-collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
