global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    metrics_path: /metrics # Default Prometheus metrics path
    static_configs:
      - targets: ["opentelemetry-collector:8889"] # Must match the prometheus exporter port
    honor_labels: true # Preserve label conflicts from OTel
